### PR TITLE
Switch back Antora to ~ version

### PR DESCRIPTION
**Pull request by pirj**
Following [this checklist](https://github.com/rubocop/rubocop-capybara/pull/2#issuecomment-1367335974)

______________________________________________________________________

Before submitting the PR make sure the following are checked:

- [x] Feature branch is up-to-date with `main` (if not - rebase it).
- [x] Squashed related commits together.
- [-] Added tests.
- [-] Updated documentation.
- [-] Added an entry to the `CHANGELOG.md` if the new code introduces user-observable changes.
- [x] The build (`bundle exec rake`) passes (be sure to run this locally, since it may produce updated documentation that you will need to commit).

### CODE REVIEW

**Comment by pirj** [comment]
I couldn't push directly to `main` 🤷 
```
Enumerating objects: 7, done.
Counting objects: 100% (7/7), done.
Delta compression using up to 4 threads
Compressing objects: 100% (4/4), done.
Writing objects: 100% (4/4), 389 bytes | 194.00 KiB/s, done.
Total 4 (delta 2), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (2/2), completed with 2 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/main.
remote: error: 10 of 10 required status checks are expected.
To github.com:rubocop/rubocop-capybara.git
 ! [remote rejected] main -> main (protected branch hook declined)
error: failed to push some refs to 'github.com:rubocop/rubocop-capybara.git'
```

I have no idea what 10/10 required status checks it tells about.

**Comment by bquorning** [comment]
> I have no idea what 10/10 required status checks it tells about.

That would be [these 10](https://github.com/rubocop/rubocop-capybara/settings/branch_protection_rules/32685368):

image

**Comment by bquorning** [comment]
Do you want to be able to push directly to `main`?

**Comment by pirj** [comment]
Not really, I'm fine with such small PRs, let's keep `main` protected from sudden mistaken pushes.

**Pull request merged**
